name: CI Angular & Cypress

on: [push]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    
    # Definir directorio de trabajo por defecto para no escribir "cd Frontend" siempre
    defaults:
      run:
        working-directory: ./Frontend

    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: Instalar Dependencias
        run: npm ci

      - name: Ejecutar Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./Frontend
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:4200'
          browser: chrome
